/**
 * KAYNAĞIN AYRI MODEL SAYDIĞI ADLAR (marka → model adları). `scripts/model-catalog.ts` kaynağın marka sayfalarındaki model listesinden
 * üretir (scrape.bat 22); elle düzenlenmez. Yalnızca genel aile kuralının ("i20 N" → "i20") yanlış birleştirdiği adlar yazılır; diğer
 * modeller zaten aile kuralıyla doğru çıkıyor. Anahtar: aksansız, harf/rakam dışı karakterleri atılmış küçük harf marka adı.
 */
export const MODEL_EXTENSIONS: Record<string, string[]> = {
  "alfaromeo": ["Junior Elettrica","Junior Ibrida"],
  "arora": ["AR-EV Pickup"],
  "askam": ["Fargo Fora"],
  "audi": ["E-Tron GT","Q3 Sportback","Q4 E-tron","Q8 E-Tron","Q8 Sportback E-Tron","RS Q8"],
  "bentley": ["Flying Spur"],
  "byd": ["Atto 2","Atto 3 EV","Seal U DM-i","Seal U EV","Sealion 7"],
  "chery": ["Omoda 5","Tiggo 7","Tiggo 7 Pro","Tiggo 7 Pro Max","Tiggo 8","Tiggo 8 Pro","Tiggo 8 Pro Max"],
  "citroen": ["C3 Picasso","C4 Cactus","C4 Grand Picasso","C4 Picasso","C4 SUV","C4 X","e-C4 X"],
  "dacia": ["Logan Pickup","Sandero Stepway"],
  "daewoo": ["Super Saloon"],
  "fiat": ["Doblo Cargo","Doblo Combi","Doblo Combi Mix","Doblo Panorama","e-Doblo Panorama","Fiorino Cargo","Fiorino Combi","Fiorino Combi Mix","Fiorino Panorama","Grande Panda Electric"],
  "ford": ["Mustang Mach-E","Puma- E","Transit Kombi"],
  "forthing": ["T5 Evo"],
  "foton": ["Tundland V9","Tunland G7"],
  "hyundai": ["Accent Blue","Accent Era","H 100","H 350","Ioniq 5","Ioniq 5 N","Ioniq 6","i20 Active","i20 N","i20 Troy","Kona Elektrik"],
  "jeep": ["Avenger Electric"],
  "kgmobility": ["Actyon Sports","Korando Sports","Musso Grand","Torres EVX"],
  "kia": ["Niro EV","Pro Ceed"],
  "lincoln": ["Town Car"],
  "mercedesbenz": ["AMG GT","Maybach S","Smart Fortwo Coupe"],
  "mg": ["Marvel R"],
  "mini": ["Cooper Clubman","Cooper Electric","Cooper S","John Cooper"],
  "mitsubishi": ["L 200","L 300","Lancer Evolution"],
  "nissan": ["Laurel Altima","Pick Up","Rally Raid","Townstar EV"],
  "opel": ["Combo Life","Crossland X","Grandland X","Mokka X","Zafira Life"],
  "peugeot": ["Expert Traveller"],
  "porsche": ["Taycan Elektrik"],
  "proton": ["Gen 2"],
  "reeder": ["Reev Fancy"],
  "regalraptor": ["K5 Long"],
  "renault": ["Express Combi","Fluence Z.E","Kangoo Express","Kangoo Multix","Megane E-Tech","R5 E-Tech","Scenic RX4","Trafic Multix","Vel Satis"],
  "skoda": ["Enyaq Coupe","Fabia Praktik","Felicia Pickup","Forman Praktik"],
  "suzuki": ["SX4 S-Cross"],
  "swm": ["G01 Pro","G01F Premium DCT","G05 Pro"],
  "tata": ["Pickup 2.0 TDI"],
  "toyota": ["Land Cruiser Prado","Proace City","Proace City Cargo","Proace Max","Proace Verso"],
  "volkswagen": ["Passat Alltrack","Passat Variant","Tiguan AllSpace"],
  "volvo": ["V40 Cross Country","V60 Cross Country","V90 Cross Country"],
};
